### ISSUE TITLE
Dom0 screenshare does not work

### ISSUE THREAD

**Issue by runephilosof-abtion** [QubesOS/qubes-video-companion#15]
When I choose dom0 as screenshare, I get this error
```
[user@work ~]$ qubes-video-companion screenshare
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 82, in <module>
    main(sys.argv)
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 17, in main
    width, height, fps = read_video_parameters()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 63, in read_video_parameters
    raise RuntimeError("wrong number of bytes read")
RuntimeError: wrong number of bytes read
```

In dom0 I have this installed
```
qubes-video-companion-dom0-1.0.5-1-fc37.noarch
```

In the appvm I have this installed
```
[user@work ~]$ sudo dnf list --installed|grep compani
qubes-video-companion.noarch                   1.0.5-1.fc39                    @qubes-vm-r4.2-current                
qubes-video-companion-docs.noarch              1.0.5-1.fc39                    @qubes-vm-r4.2-current                
qubes-video-companion-license.noarch           1.0.5-1.fc39                    @qubes-vm-r4.2-current                
qubes-video-companion-receiver.noarch          1.0.5-1.fc39                    @qubes-vm-r4.2-current                
qubes-video-companion-sender.noarch            1.0.5-1.fc39                    @qubes-vm-r4.2-current                
```

**Comment by pgerber** [comment]
I'm experiencing the same issue. Message from dom0:

```
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]: Traceback (most recent call last):
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:   File "/usr/share/qubes-video-companion/sender/screenshare.py", line 81, in <module>
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:     screenshare = ScreenShare()
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:                   ^^^^^^^^^^^^^
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:   File "/usr/share/qubes-video-companion/sender/screenshare.py", line 24, in __init__
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:     self.main(self)
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:   File "/usr/share/qubes-video-companion/sender/service.py", line 157, in main
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:     self.start_service(target_domain, remote_domain)
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:   File "/usr/share/qubes-video-companion/sender/service.py", line 51, in start_service
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]:     Notify.Notification.new(app, msg, icon).show()
Mar 29 22:49:29 dom0 qvc.ScreenShare+-disp163[21016]: gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```

**Comment by pgerber** [comment]
Okay, adding DBUS_SESSION_BUS_ADDRESS to /etc/qubes-rpc/qvc.ScreenShare fixes the issue:

```
#!/usr/bin/sh --

# Copyright (C) 2021 Elliot Killick <elliotkillick@zohomail.eu>
# Copyright (C) 2021 Demi Marie Obenour <demi@invisiblethingslab.com>
# Licensed under the MIT License. See LICENSE file for details.
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus   # <-- added
exec python3 -- /usr/share/qubes-video-companion/sender/screenshare.py
```
